language: generic
sudo: false
install: true
script: true
notifications:
  irc:
    channels:
      - secure: ID0E7MUn0CD8tclJzw4T/BJCHO2jh9EAL88A4K/NontgwNkUFzjC5BGY4ilR8fQ0JQ8OO0d8k6xPK51QqBVi+CZ5Vm1uUtbbg/MrMNRVFU9GyK+RoJwBNV8xr977dLZYuYgUy4foklVxrN3rssDDjECVOga9PrLg0xTyWQCcrG/OTFh6audjj/BvrtlLWmbbh2tsOfp72q/6vaV8P/CSlL6wDl0OUJbnkefNrn/k5WVoYCLN1UJ8IJn6q+BB4O+AuLeaJXMal4CcEuqYGsd7DFzxpG7JEGeAqa2x73hO9f0T6Il5D42FC1/ms00sJDSxsUF3NgkZBzf6upPoL4S+p0hJV4q4NiNKa4JT7SYr/JBY915z1bk2ZPjnI6buJcg566BHJxQ0Wmi6f5gzKwVhvFQ8Fq8ourc60I+zvdjWLdrakU7q8+bXzSEe1a+/ngBDR9PZEt9nnPhLS5v6GVasY8vX1WzS41vFjtT7Cgj1SzaSGE/Wq67HO9EQJLLe7MwmippRr7QZearpe31dhH58CHarXd8zwHElGevV3pU9HfmEDFBopXr4NhyNWcTGga3/uicDReN6JJqhErZtZG/3Q2RXYtyDxOKpaa8K+u5ZRthsfIalmKKDgc+LA/OJp8KuQjriHqAjF+CJ8WWcfsvvGwVsUdra7sZM3FwX1Usu/6U=
    nick: Cardstock
    on_success: always
    on_failure: always
    password:
      secure: VO0pjVpkBg/6q1qcbdrDATji6H4THGvlAKAPWZFulsGIjcaYuai1eYWtzh8tGCR/ZfdwJe9A9pZ0EGVtoG10f5RkztJr5Bk0S3aY79lAkmtOIaNwQl5B2doX9/nzl8A9UOlPxhpLU4bHQXyidGoqQq6+LgDC6QT4nG4kSikcvH0+VExSZZ1GIbtZPyJOsa6/Uj8HFI4Q/ArtosUfD1YFb1jZRB3ZXrE4QXpPFN9zT69DgrpxuKkWB2L0hNTwWTcpyIGKtULeTZE+fELyXN9uPAoVDWVARMjE/Tdve7LXv6XblVn4QeZYB+evWv3n/UBmxZ4rJ6Kxdd4vnbZd8gpMVfxJ87jIwfu1r6UEUuW7HUXVc5FCwiPlsEszH1nmn+9ZyIYIefKNnqDSsaY/VbXRoqN5bnWn90h3O7Liv3cBgpMXU/tZyR67bsU1bymldPfk/Dm/Km8g8ahiXFsLVeHxGkS7wx07sUoXhnZP0lHhkWpUVQViCsGjjLqJiwzaROsJvqcN3J9RVFz3fjnfPIC5IRir0tqRcg16PtLvwo30iABuPOPJXeLtgfrUJ84HtRnQrSUoS80Py9sTStTtMHhMKARQJhs9gVpUqPxXLAA0xP2c6D+XQozCNyanjkzJwutj1IbVkcqY5nYWimq6aSnoXrucCsAv8a6x43naVkqXkOE=
