language: generic
sudo: false
install: true
script: true
notifications:
  irc:
    channels:
    - secure: kW3iUCq1UXrXymx0Wt2UiLvo44Ou6m9O/2vpfl4m+hUWjPuCl0ctsy3JZiuVfliMWdVmeYnM8Fv9tJR22Ao4ofSbtKTZynScTdXa5lBPI3GNiSaG+GRPFYxxu2021+Z/gQJAMld+oQ0s/eA2UiZnMcb9M8liOyrSwlVFbrBtnrdzBQ+XIZ8yWeoKiqXXCXKZgTLDpyMSFyVC6u8wj/1Ufz5dM5sbcdat9mN7LLmxSsY+d8PHs/fDRrouWjeTV1rNvqEopSeb39YWv2UwpoJT5JwvzkGm3agPIxb2PvyIT1TeeBU+7r8lNCiiyvHtiPZpwpV758Y/veZIR+VWl+n31ikYcZLb5lfPPbVTiq8iUlxAZEYtF68QlfAQ/1qjOGNs0PYGqluGRUqTfTLrwIp8jlYcJwrvU1epuJP51ek10FpPmEsTkiOi3VAVc3X1mtBSuW44oAXFL+EoFHvliu62jwFJtmkbHzrSf5L/GSRhIMby7mp3FDhiWnq1/vJWTFzlpHKcXY2k0wxNq6nT5NC9UD8nYWS5KUoc2fzx3PgIM3a17a8i/ndIj+4Sizo4WPaDKFS2V9v8vYaBky8Xqkx0sclg4jQxdPV9iIcVuSpGuEJkpM7QJSqTQOyNQR7BaeNAIP6NS4oOwERjFEA6QTsOxnk/CL7lAVEVDRAkAn+R0po=
    on_success: always
    on_failure: always
    password:
      secure: VO0pjVpkBg/6q1qcbdrDATji6H4THGvlAKAPWZFulsGIjcaYuai1eYWtzh8tGCR/ZfdwJe9A9pZ0EGVtoG10f5RkztJr5Bk0S3aY79lAkmtOIaNwQl5B2doX9/nzl8A9UOlPxhpLU4bHQXyidGoqQq6+LgDC6QT4nG4kSikcvH0+VExSZZ1GIbtZPyJOsa6/Uj8HFI4Q/ArtosUfD1YFb1jZRB3ZXrE4QXpPFN9zT69DgrpxuKkWB2L0hNTwWTcpyIGKtULeTZE+fELyXN9uPAoVDWVARMjE/Tdve7LXv6XblVn4QeZYB+evWv3n/UBmxZ4rJ6Kxdd4vnbZd8gpMVfxJ87jIwfu1r6UEUuW7HUXVc5FCwiPlsEszH1nmn+9ZyIYIefKNnqDSsaY/VbXRoqN5bnWn90h3O7Liv3cBgpMXU/tZyR67bsU1bymldPfk/Dm/Km8g8ahiXFsLVeHxGkS7wx07sUoXhnZP0lHhkWpUVQViCsGjjLqJiwzaROsJvqcN3J9RVFz3fjnfPIC5IRir0tqRcg16PtLvwo30iABuPOPJXeLtgfrUJ84HtRnQrSUoS80Py9sTStTtMHhMKARQJhs9gVpUqPxXLAA0xP2c6D+XQozCNyanjkzJwutj1IbVkcqY5nYWimq6aSnoXrucCsAv8a6x43naVkqXkOE=
